server:
  port: 0

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 1234qwer

mybatis-plus:
  type-aliases-package: com.hoby.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
