server:
  # 服务端口
  port: 8888

spring:
  application:
    # 服务名
    name: sharding-sphere-demo
  # 分库分表配置
  shardingsphere:
    mode:
      type: Memory
    datasource:
      names: ds0,ds1,ds2  # 数据源名称
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: "jdbc:mysql://192.168.139.130:3306/sharding_demo_0?useUnicode=true&characterEncoding=utf8\
                            &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8\
                            &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true"
        username: "root"
        password: "%TGB6yhn"
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: "jdbc:mysql://192.168.139.131:3306/sharding_demo_1?useUnicode=true&characterEncoding=utf8\
                            &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8\
                            &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true"
        username: "root"
        password: "%TGB6yhn"
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: "jdbc:mysql://192.168.139.132:3306/sharding_demo_2?useUnicode=true&characterEncoding=utf8\
                            &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8\
                            &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true"
        username: "root"
        password: "%TGB6yhn"
    rules:  # 分库分表规则配置
      sharding:
        default-database-strategy:  # 分库策略
          standard:
            sharding-column: user_id  # 按照分库的列
            sharding-algorithm-name: user-id-inline  # 分库算法名称(使用yml不能包含下划线,否则不生效)
        tables:
          us_admin:  # 数据库表名前缀
            actual-data-nodes: ds$->{0..2}.us_admin$->{0..1}  # 实际表名
            table-strategy:  # 分表策略
              standard:
                sharding-column: addr_id  # 按照分表的列
                sharding-algorithm-name: addr-id-inline  # 分表算法名称(使用yml不能包含下划线,否则不生效)
            key-generate-strategy:
              column: id  # 主键列
              key-generator-name: snowflake  # 主键生成算法名称
        sharding-algorithms:
          user-id-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{user_id % 3}  # 分库算法(取模)
          addr-id-inline:
            type: INLINE
            props:
              algorithm-expression: us_admin$->{addr_id % 2}  # 分表算法(取模)
        key-generators:
          snowflake:
            type: SNOWFLAKE
    props:
      sql-show: true  # 展示执行sql
